on:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev branch into main
        run: |
          git fetch origin dev
          git merge origin/dev --no-ff -m "Merge dev into main from workflow"
          
      - name: Push updated main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm i

      - name: Install Supabase JS client
        run: npm install @supabase/supabase-js

      - name: Make fetch script executable
        run: chmod +x scripts/fetch-hidden-tests.sh

      - name: Fetch S3 URL and download hidden test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_KEY }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: ./scripts/fetch-hidden-tests.sh

      - name: Make script executable
        run: chmod +x scripts/run-tests.sh

      - name: Run tests with minimal output
        run: scripts/run-tests.sh
        continue-on-error: true

      - name: Show Test Summary (Passed/Failed/Total)
        run: |
          echo "Test Summary:"
          cat ./results.json | jq '{
            passed: .numPassedTests,
            failed: .numFailedTests,
            total: .numTotalTests
          }'
      - name: Make script executable
        run: chmod +x scripts/update-results.sh
      - name: Upload results to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_API_KEY: ${{ secrets.SUPABASE_KEY }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: scripts/update-results.sh
        
        