name: CI

on:
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [ "main" ]
  push:
    branches:
      - main 
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm i

      - name: Make script executable
        run: chmod +x scripts/update-pr.sh

      - name: Run update-pr script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: ./scripts/update-pr.sh
      